@startuml
'https://plantuml.com/state-diagram
[*] --> 表单1: 填写
[*] --> 表单2: 填写(异步)

表单1 --> 消息中间件
表单2 --> 消息中间件
医疗设备 --> 消息中间件
数据库 --> 消息中间件
... --> 消息中间件

消息中间件 --> 算法定义

state 算法定义 {
  输入1 --> 节点C
  输入2 --> 节点C
  节点C --> 节点D
  输入3 --> 节点D
}
算法定义 -> 界面: 订阅
@enduml